twig:
    default_path: '%kernel.project_dir%/templates'
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    paths:
        "%kernel.root_dir%/../vendor/sonata-project/admin-bundle/src/Resources/views": SonataAdmin
        "%kernel.root_dir%/../templates": App
        "%kernel.root_dir%/../vendor/piedweb/cms-bundle/src/Resources/views/FOSUserBundle/views": FOSUser
        "%kernel.root_dir%/../vendor/piedweb/cms-bundle/src/Resources/views/TwigBundle": Twig
    form_themes:
        - 'bootstrap_4_layout.html.twig'
        - '@SonataCore/Form/datepicker.html.twig'
    globals:
        img_dir: "%media_dir_absolute%/"
        logo_alt: "%app.name%"
        app_contact_email: "%app.contact.email%"
        app_color: "%app.color"
#        app_contact_adress: "%app.contact.adress%"
